/**
 * Claude Adapter
 * Discovers and parses Claude Code .jsonl session files into structured records.
 */

import { readdirSync, statSync, existsSync } from 'fs';
import { join, resolve, normalize, sep, dirname } from 'path';
import { Provider, SourceFile, ParsedSession, SessionRecord } from '../models';

const SKIP_DIRS = new Set(['memory']);

function defaultRoots(): string[] {
  const home = require('os').homedir();
  return [join(home, '.claude', 'projects')];
}

export const DEFAULT_ROOTS = defaultRoots();

// ---------------------------------------------------------------------------
// Utility helpers
// ---------------------------------------------------------------------------

function parseDateTime(value: string): Date | null {
  if (!value) return null;
  const normalized = value.replace('Z', '+00:00');
  try {
    return new Date(normalized);
  } catch {
    return null;
  }
}

function substantiveText(text: string): boolean {
  return Boolean(text && text.trim());
}

function truncateForDisplay(text: string, maxChars: number): string {
  text = text.trim();
  if (text.length <= maxChars) return text;
  return text.substring(0, maxChars).trimEnd() + '…';
}

function previewFromText(text: string): string {
  text = text.trim().replace(/\n/g, ' ');
  return truncateForDisplay(text, 120);
}

function normalizePath(path: string): string {
  return resolve(path).split(sep).join('/');
}

function findRepoRoot(cwd: string): string | null {
  let current = resolve(cwd);
  const visited = new Set<string>();

  while (current && !visited.has(current)) {
    visited.add(current);
    if (existsSync(join(current, '.git'))) {
      return current.split(sep).join('/');
    }
    const parent = dirname(current);
    if (parent === current) break;
    current = parent;
  }

  return null;
}

function summarizeToolInput(block: any): string {
  const name = block.name || 'unknown';
  const inp = block.input || {};

  const target =
    inp.command ||
    inp.file_path ||
    inp.path ||
    inp.pattern ||
    inp.query ||
    inp.prompt ||
    '';

  if (target) {
    const strTarget = String(target).trim();
    return `[tool: ${name}] ${strTarget.length > 120 ? strTarget.substring(0, 117) + '...' : strTarget}`;
  }

  return `[tool: ${name}]`;
}

function extractText(message: any): string {
  const content = message.content || '';
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) {
    const parts: string[] = [];
    for (const block of content) {
      if (!block || typeof block !== 'object') continue;
      const btype = block.type;
      if (btype === 'text') {
        parts.push(block.text || '');
      } else if (btype === 'tool_use') {
        parts.push(summarizeToolInput(block));
      } else if (btype === 'tool_result') {
        const inner = block.content || '';
        if (typeof inner === 'string') {
          parts.push(inner);
        } else if (Array.isArray(inner)) {
          for (const sub of inner) {
            if (sub && typeof sub === 'object' && sub.type === 'text') {
              parts.push(sub.text || '');
            }
          }
        }
      }
    }
    return parts.join('\n');
  }
  return '';
}

function formatTranscriptLine(role: string, ts: Date | null, text: string): string {
  const tsStr = ts ? ts.toISOString() : 'unknown';
  return `[${tsStr}] ${role.toUpperCase()}: ${text}`;
}

function tagContent(text: string, tag: string): string {
  const openTag = `<${tag}>`;
  const closeTag = `</${tag}>`;
  const start = text.indexOf(openTag);
  if (start === -1) return '';
  const innerStart = start + openTag.length;
  const end = text.indexOf(closeTag, innerStart);
  if (end === -1) return '';
  return text.substring(innerStart, end);
}

function stripCommandMarkup(text: string): string {
  if (!text.includes('<command-name>')) return text;
  return tagContent(text, 'command-args').trim();
}

function shouldSkipMessage(value: any, text: string): boolean {
  const normalized = text.trim();
  const isMeta = Boolean(value.isMeta);
  const isLocalCommandCaveat =
    isMeta &&
    (normalized.includes('<local-command-caveat>') ||
      normalized.startsWith(
        'Caveat: The messages below were generated by the user while running local commands.'
      ));

  const isCommandBookkeeping =
    normalized.includes('<command-name>') && !tagContent(normalized, 'command-args').trim();

  return isLocalCommandCaveat || isCommandBookkeeping;
}

function minimalRecord(path: string, error: string): ParsedSession {
  const stem = path.split('/').pop() || 'unknown';
  const session: SessionRecord = {
    id: `claude:${stem}`,
    provider: Provider.CLAUDE,
    providerSessionId: stem,
    title: null,
    summary: null,
    cwd: null,
    repoRoot: null,
    createdAt: null,
    updatedAt: null,
    lastMessageAt: null,
    previewText: `(parse error: ${error})`,
    sourcePath: normalizePath(path),
    messageCount: null,
    model: null,
    inputTokens: null,
    outputTokens: null,
    cachedInputTokens: null,
    cacheCreationTokens: null,
    cacheCreation1hTokens: null,
    reasoningTokens: null,
    totalTokens: null,
    gitBranch: null,
    cliVersion: null,
    parseVersion: 'claude-v1',
    rawMetadataJson: null,
    parseWarning: error,
    discoverySource: 'jsonl',
  };

  return {
    session,
    transcriptText: '',
  };
}

// ---------------------------------------------------------------------------
// Adapter
// ---------------------------------------------------------------------------

export interface ClaudeAdapterOptions {
  roots?: string[];
}

export class ClaudeAdapter {
  readonly roots: string[];

  constructor(options: ClaudeAdapterOptions = {}) {
    this.roots = options.roots || DEFAULT_ROOTS;
  }

  // ------------------------------------------------------------------
  // Discovery
  // ------------------------------------------------------------------

  discover(): SourceFile[] {
    const files: SourceFile[] = [];

    for (const root of this.roots) {
      if (!existsSync(root)) continue;

      const walk = (dir: string): void => {
        const entries = readdirSync(dir, { withFileTypes: true });

        for (const entry of entries) {
          if (entry.isDirectory()) {
            if (!SKIP_DIRS.has(entry.name)) {
              walk(join(dir, entry.name));
            }
          } else if (entry.isFile() && entry.name.endsWith('.jsonl')) {
            const path = join(dir, entry.name);
            try {
              const stat = statSync(path);
              files.push({
                provider: Provider.CLAUDE,
                path: normalizePath(path),
                mtimeNs: BigInt(Math.floor(stat.mtimeMs * 1_000_000)),
                sizeBytes: stat.size,
              });
            } catch {
              // Skip files that can't be read
            }
          }
        }
      };

      walk(root);
    }

    return files;
  }

  // ------------------------------------------------------------------
  // Parsing
  // ------------------------------------------------------------------

  parse(source: SourceFile): ParsedSession {
    try {
      return this.parseInner(source.path);
    } catch (exc) {
      return minimalRecord(source.path, exc instanceof Error ? exc.message : String(exc));
    }
  }

  private parseInner(path: string): ParsedSession {
    const fs = require('fs');
    const raw = fs.readFileSync(path, 'utf-8');

    let providerSessionId = path.split('/').pop() || 'unknown';
    let cwd: string | null = null;
    let createdAt: Date | null = null;
    let updatedAt: Date | null = null;
    const messages: { role: string; text: string; timestamp: Date | null }[] = [];
    const transcriptLines: string[] = [];
    let lastPrompt: string | null = null;
    let summary: string | null = null;

    // Token / model accumulators
    let model: string | null = null;
    let inputTokens = 0;
    let outputTokens = 0;
    let cachedInputTokens = 0;
    let cacheCreationTokens = 0;
    let cacheCreation1hTokens = 0;
    let gitBranch: string | null = null;
    let cliVersion: string | null = null;

    for (const line of raw.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed) continue;

      let value: any;
      try {
        value = JSON.parse(line);
      } catch {
        continue;
      }

      // Session ID
      if (value.sessionId) {
        providerSessionId = String(value.sessionId);
      }

      // Summary
      if (summary === null && value.summary) {
        const rawSummary = value.summary;
        if (typeof rawSummary === 'string' && substantiveText(rawSummary)) {
          summary = rawSummary;
        }
      }

      // Last prompt
      if (value.type === 'last-prompt') {
        const prompt = (value.lastPrompt || '').trim();
        if (substantiveText(prompt)) {
          lastPrompt = prompt;
        }
      }

      // Working directory
      if (cwd === null && value.cwd) {
        cwd = String(value.cwd);
      }

      // Git branch and version (first occurrence wins)
      if (gitBranch === null && value.gitBranch) {
        gitBranch = String(value.gitBranch);
      }
      if (cliVersion === null && value.version) {
        cliVersion = String(value.version);
      }

      const timestamp = parseDateTime(value.timestamp || '');

      // Extract model and token usage from assistant messages
      if (value.message && typeof value.message === 'object') {
        const msg = value.message;
        if (model === null && msg.model) {
          model = String(msg.model);
        }
        const usage = msg.usage;
        if (usage && typeof usage === 'object') {
          inputTokens += usage.input_tokens || 0;
          outputTokens += usage.output_tokens || 0;
          cachedInputTokens += usage.cache_read_input_tokens || 0;
          const cacheCreation = usage.cache_creation;
          const cacheCreation5mTokens =
            cacheCreation && typeof cacheCreation === 'object'
              ? cacheCreation.ephemeral_5m_input_tokens
              : null;
          const cacheCreation1hTokensForMessage =
            cacheCreation && typeof cacheCreation === 'object'
              ? cacheCreation.ephemeral_1h_input_tokens || 0
              : 0;
          const cacheCreationTotal = usage.cache_creation_input_tokens || 0;
          cacheCreationTokens +=
            cacheCreation5mTokens != null
              ? cacheCreation5mTokens
              : Math.max(0, cacheCreationTotal - cacheCreation1hTokensForMessage);
          cacheCreation1hTokens += cacheCreation1hTokensForMessage;
        }
      }

      // Determine role and text
      let role: string | null = value.type;
      let text = '';

      if (value.message) {
        if (typeof value.message === 'object') {
          role = value.message.role || role;
          text = extractText(value.message);
        }
      } else if (typeof value.content === 'string') {
        text = value.content;
      }

      if (shouldSkipMessage(value, text)) continue;

      text = stripCommandMarkup(text);

      if (role === 'user' || role === 'assistant') {
        text = text.trim();
        if (!text) continue;

        if (createdAt === null) createdAt = timestamp;
        if (timestamp) updatedAt = timestamp;

        messages.push({ role, text, timestamp });
        transcriptLines.push(formatTranscriptLine(role, timestamp, text));
      }
    }

    // Derive title / preview from messages
    const firstUserText = messages.find(m => m.role === 'user' && substantiveText(m.text))?.text || null;
    const lastUserText = [...messages].reverse().find(m => m.role === 'user' && substantiveText(m.text))?.text || null;

    const titleSource = lastPrompt || lastUserText || firstUserText;
    const title = titleSource ? truncateForDisplay(titleSource, 100) : null;

    if (summary === null) {
      summary = firstUserText ? truncateForDisplay(firstUserText, 180) : null;
    } else {
      summary = truncateForDisplay(summary, 180);
    }

    const previewSource = lastPrompt || lastUserText || firstUserText;
    const preview = previewSource ? previewFromText(previewSource) : '(no preview available)';

    const repoRoot = cwd ? findRepoRoot(cwd) : null;

    const totalTokens = (inputTokens || 0) + (outputTokens || 0) || null;

    const rawMetadataJson = JSON.stringify({
      lineCount: raw.split('\n').length,
      sessionPath: normalizePath(path),
      model,
      inputTokens: inputTokens || null,
      outputTokens: outputTokens || null,
      cachedInputTokens: cachedInputTokens || null,
      cacheCreationTokens: cacheCreationTokens || null,
      cacheCreation1hTokens: cacheCreation1hTokens || null,
      gitBranch,
    });

    const session: SessionRecord = {
      id: `claude:${providerSessionId}`,
      provider: Provider.CLAUDE,
      providerSessionId,
      title,
      summary,
      cwd,
      repoRoot,
      createdAt,
      updatedAt,
      lastMessageAt: updatedAt,
      previewText: preview,
      sourcePath: normalizePath(path),
      messageCount: messages.length,
      model,
      inputTokens: inputTokens || null,
      outputTokens: outputTokens || null,
      cachedInputTokens: cachedInputTokens || null,
      cacheCreationTokens: cacheCreationTokens || null,
      cacheCreation1hTokens: cacheCreation1hTokens || null,
      reasoningTokens: null,
      totalTokens,
      gitBranch,
      cliVersion,
      parseVersion: 'claude-v1',
      rawMetadataJson,
      parseWarning: null,
      discoverySource: 'jsonl',
    };

    return {
      session,
      transcriptText: transcriptLines.join('\n\n'),
    };
  }
}
